spring:
  application:
    name: swm_refactoring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true # https://chaewsscode.tistory.com/174, https://velog.io/@wlsh44/Spring-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%B4%88%EA%B8%B0%ED%99%94
  sql:
    init:
      mode: embedded
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dnalgustjr!
  thymeleaf:
    cache : false

security:
  encryption:
    secret-key: "b2d6f5c79a2b2f1db939f04e3dbd6d9bdb56c07b557073d2a0c24fd4faec0a4f"